### ISSUE TITLE
[🐛 bug report] `ptracer` does not match `path` on Cornell Box

### ISSUE THREAD

**Issue by merlinND** [mitsuba-renderer/mitsuba3#42]
## Summary

Despite `ptracer` matching `path` on the (supposedly) more complex scene `various_emitters.xml`...

![image](https://user-images.githubusercontent.com/5563370/137754664-4c57b939-c1fc-41a4-b945-79baf3e0fa7f.png)
![image](https://user-images.githubusercontent.com/5563370/137754678-7f01ec4e-2bad-4e3e-9977-0e3473b714f7.png)

...it does not match it on `cbox.xml` starting from `max_depth = 2`:

- ptracer (brighter)
 
![image](https://user-images.githubusercontent.com/5563370/137754868-2c683ca8-2886-4215-913b-0c6a8061ef11.png)

- path

![image](https://user-images.githubusercontent.com/5563370/137754905-88ac8b5d-9a05-490c-873c-b4844d5b2d6a.png)

## System configuration

- Compiled variants:
    * `scalar_rgb`

## Steps to reproduce

```
for int in ptracer path; do
    mitsuba -m scalar_rgb ../resources/data/scenes/cbox/cbox.xml -o cbox-$int.exr -Dspp=1024 -Dmax_depth=2 -Dintegrator=$int; 
done
```

## TODOs

- [x] Test when specifying the emitters brightness as a scalar value instead of an interpolated spectrum → same issue
- [ ] Try different variants
- [x] Try to reproduce the situation in `various_emitters.xml` (which also contains an area emitter) → can reproduce, but only when replacing the analytic `rectangle` with an `obj` rectangle. The larger the area of the shape, the larger the difference.
- [x] Check if this is related to cbox specifying colors as spectra rather than RGB → same issue with `cbox-rgb.xml`
- [ ] Fix area lights for non-trivial meshes
