### ISSUE TITLE
[🐛 bug report] Particle tracer issues

### ISSUE THREAD

**Issue by merlinND** [mitsuba-renderer/mitsuba3#45]
## TODOs

- [x] Identify and fix brightness issue from #42 → fixed in #43
- [ ] If possible, fix shading normals issue from #42
- [ ] Update render test references
- [ ] Check if other emitters need ray offsets
- [x] Fix test failures from #41
- [x] `Envmap::sample_ray()`: fix `si.wi` being used in `eval()` but not being set, and incorrect sampling direction → https://github.com/mitsuba-renderer/mitsuba2-next/pull/48#issuecomment-963028891
